### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [libyal/libmsiecf#1]
I am  a developer for the archassault project and we are workign on adding this to our repo to bring in plaso and dfvfs. We have everything compiled from source except this one library. Do you think you can tag a new release so that we can build off the current git master? We have successfully built off the git master, but we would prefer a tagged release if possible. We realize its still in beta, but we have been requested to add it by our users.

**Comment by joachimmetz** [comment]
So the last tagged release is: https://github.com/libyal/libmsiecf/releases/tag/20141025 as you can see here the number of changes since then is minimal https://github.com/libyal/libmsiecf/compare/20141025...master.

I therefore fail to see the importance of a tagged release from HEAD? Or do you need it because of the synclibs.sh changes?

**Comment by archey** [comment]
We need it because of the synclib changes to build the pkg.

**Comment by joachimmetz** [comment]
So I really urge you to use the [packaged version](https://github.com/libyal/libmsiecf/releases/download/20141025/libmsiecf-alpha-20141025.tar.gz) instead of the github generated packages for distribution. Primarily since the dependencies provided via synclibs.sh will change and potential could break your build.

However I'm willing to create a new package for you this weekend if you really want to pursue your approach.

**Comment by archey** [comment]
We are using the pkged version, but it will not compile properly. It 
fails due to this error:

gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include 
-I../common -I../libcstring -I../libcerror -I../libcthreads 
-I../libcdata -I../libcnotify -I../libuna -I../libfdatetime 
-I../libfguid @LIBFWNT_CPPFLAGS@ -D_FORTIFY_SOURCE=2 -march=x86-64 
-mtune=generic -O3 -pipe -fstack-protector-all --param=ssp-buffer-size=4 
-Wall -MT libfvalue_error.lo -MD -MP -MF .deps/libfvalue_error.Tpo -c 
libfvalue_error.c  -fPIC -DPIC -o .libs/libfvalue_error.o
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include 
-I../common -I../libcstring -I../libcerror -I../libcthreads 
-I../libcdata -I../libcnotify -I../libuna -I../libfdatetime 
-I../libfguid @LIBFWNT_CPPFLAGS@ -D_FORTIFY_SOURCE=2 -march=x86-64 
-mtune=generic -O3 -pipe -fstack-protector-all --param=ssp-buffer-size=4 
-Wall -MT libfvalue_integer.lo -MD -MP -MF .deps/libfvalue_integer.Tpo 
-c libfvalue_integer.c  -fPIC -DPIC -o .libs/libfvalue_integer.o
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
Makefile:657: recipe for target 'libfvalue_binary_data.lo' failed
make[1]: **\* [libfvalue_binary_data.lo] Error 1
make[1]: **\* Waiting for unfinished jobs....
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include 
-I../common -I../libcstring -I../libcerror -I../libcthreads 
-I../libcdata -I../libcnotify -I../libuna -I../libfdatetime 
-I../libfguid @LIBFWNT_CPPFLAGS@ -D_FORTIFY_SOURCE=2 -march=x86-64 
-mtune=generic -O3 -pipe -fstack-protector-all --param=ssp-buffer-size=4 
-Wall -MT libfvalue_split_string.lo -MD -MP -MF 
.deps/libfvalue_split_string.Tpo -c libfvalue_split_string.c  -fPIC 
-DPIC -o .libs/libfvalue_split_string.o
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
Makefile:657: recipe for target 'libfvalue_filetime.lo' failed
make[1]: **\* [libfvalue_filetime.lo] Error 1
Makefile:657: recipe for target 'libfvalue_string.lo' failed
make[1]: **\* [libfvalue_string.lo] Error 1
gcc: error: @LIBFWNT_CPPFLAGS@: No such file or directory
Makefile:657: recipe for target 'libfvalue_data_handle.lo' failed
make[1]: **\* [libfvalue_data_handle.lo] Error 1
Makefile:657: recipe for target 'libfvalue_floating_point.lo' failed
make[1]: **\* [libfvalue_floating_point.lo] Error 1
Makefile:657: recipe for target 'libfvalue_error.lo' failed
make[1]: **\* [libfvalue_error.lo] Error 1
Makefile:657: recipe for target 'libfvalue_integer.lo' failed
make[1]: **\* [libfvalue_integer.lo] Error 1
Makefile:657: recipe for target 'libfvalue_split_string.lo' failed
make[1]: **\* [libfvalue_split_string.lo] Error 1
make[1]: Leaving directory 
'/home/spirit/packages/plaso/libsmiecf/src/libmsiecf-20141025/libfvalue'
Makefile:720: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

Build instructions:

build() {
   cd "$srcdir"/${pkgname}-${pkgver}
   ./synclibs.sh
   ./autogen.sh
   PYTHON_VERSION="2" ./configure --prefix=/usr --disable-rpath 
--enable-verbose-output --enable-debug-output --enable-python
   export LIBFWNT_CPPFLAGS=$CPPFLAGS
   make
}

package() {
   cd "$srcdir"/${pkgname}-${pkgver}
   make DESTDIR="${pkgdir}" install
}

I have to use synclibs as none of the libs seem to want to compile 
without using the synclibs.sh script in each pkged release.

Thanks
Arch3y

**Comment by joachimmetz** [comment]
So what you are referring to as packaged version is the github generated download packages. Alas I cannot turn these off (or have not found the way to do that yet). This is primarily an annoying github way of doing things. Besides the github generated packages there is a "make dist" generated package this is the one I'm referring to (see the link I sent before). The make dist package does NOT rely on ./synclibs.sh or ./autogen.sh so it does not contain these scripts.

**Comment by archey** [comment]
Ok I see now, yes I was using the github packaged version. If I use the 
link you provided, everything compiles without issue.

Thanks for your help, apologies for using the wrong package.
Arch3y

**Comment by archey** [comment]
Quick question, since we are packaging up pretty much all of your libs. 
Do you want us to use the -alpha release for each lib? Because most of 
them I have used the github pkged version and it has worked fine except 
for libolecf and libmsicef.

Thanks
Tyler

**Comment by joachimmetz** [comment]
> Thanks for your help, apologies for using the wrong package.

No worries, I blame the github UI for the cause of this confusion ;)

The meaning of the alpha status is explained here: https://github.com/libyal/libyal/wiki. Some people have mentioned this is a conservative approach others mentioned that more projects should adopt the same approach. So IMO you're free to interpret this in whatever fits your packaging model. Personally I would stick with the versioning I use since that is most consistent to end-users.

**Comment by archey** [comment]
Sounds good to me, we have all of the other libs built using the source 
code from gh. But if we have issues, we will repackage it using the 
alpha code. We are ready to release plaso and dfvfs, but we are waiting 
on the tsk patch for sleuthkit and adding python support to libwef in 
the arch repos.

Thanks
Arch3y

**Comment by joachimmetz** [comment]
So a couple of points:
- the libewf version in github git is the experimental version, which is still VERY experimental, I opt to use the packaged stable version found [here](http://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/) instead.
- as mentioned [here](http://code.google.com/p/pytsk/wiki/BuildingSleuthKit) the patch for SleuthKit 4.1.3 can be found [here](https://googledrive.com/host/0B3fBvzttpiiScUxsUm54cG02RDA/tsk4.1.3_external_type.patch). I heard Brian mention a SleuthKit 4.2 release Jun/Jul this year and it is still not there, I would suggest not waiting for it. Either use their latest development version or a patched 4.1.3.

**Comment by archey** [comment]
Yep we are using the googledrive version of libewf with --enable-python 
this is in the archlinux repos we are working with the archlinux devs to 
get the --enable-python option added and compiled in
We have patched sleuthkit 4.1.3 with the required tsk patch, however it 
is also in archlinux and we are hoping they will add the patch as well.

Thanks
