### ISSUE TITLE
Cache directory table from pymsiecf

### ISSUE THREAD

**Issue by jahrome** [libyal/libmsiecf#2]
Hi Joachim. Is the access to the cache directory table implemented in python bindings ?

**Comment by joachimmetz** [comment]
Could be that I've not implemented this yet, I'll try to have look when time permits.

**Comment by joachimmetz** [comment]
Initial support added in: https://github.com/libyal/libmsiecf/commit/3a3e3c6cada483dca2ddb607a88d9ce7f63b6499

To do:
- fix msvscpp files: https://ci.appveyor.com/project/joachimmetz/libmsiecf/build/11

**Comment by joachimmetz** [comment]
I've added the functionality, however still needs to be tested.

**Comment by jahrome** [comment]
It worked correctly with my first tests so I'm going to try it in production.

Just one issue to note when accessing cache_directories directly:

```
In [1]: import pymsiecf

In [2]: a=pymsiecf.open('index.dat')

In [3]: a.get_number_of_cache_directories()
Out[3]: 4

In [4]: a.cache_directories
Segmentation fault (core dumped)
```

Thank you for this addition.

**Comment by joachimmetz** [comment]
cache directories iterator object issue should be fixed now.
