### ISSUE TITLE
Reading data when filename is empty (?) libmsiecf-alpha-20160421

### ISSUE THREAD

**Issue by azerg** [libyal/libmsiecf#3]
Trouble:
_data_, associated with url header is useful because it stores page title at least. But in some cases (really in all my sample files), when _data_size\data_ **are present** i cant get them using your lib. 

In _libmsiecf_url.c_ in function _libmsiecf_url_get_data_size_ you have following code:

> if( ( (libmsiecf_url_values_t *) internal_item->value )->filename == NULL )
>   {
>       return( 0 );
>   }
>   if( data_size == NULL )
>   {
>       libcerror_error_set(
>        error,
>        LIBCERROR_ERROR_DOMAIN_ARGUMENTS,
>        LIBCERROR_ARGUMENT_ERROR_INVALID_VALUE,
>        "%s: invalid data size.",
>        function );
> 
> ```
>   return( -1 );
> ```
> 
>   }
>   *data_size = ( (libmsiecf_url_values_t *) internal_item->value )->data_size;

Dont know why _data_size_ depends on _filename_ so much ( actually _data_ dont instead of _data_size_ )

As simple solution i've removed

> if( ( (libmsiecf_url_values_t *) internal_item->value )->filename == NULL )
>   {
>       return( 0 );
>   }

 from the code above.

So the question is, why do you make data_size dependent of filename, so we could miss _data\data_size_ even if they present ?
I can attach sample files where _filename_ is empty, but _data\data_size_ present if needed. #

**Comment by joachimmetz** [comment]
@azerg adding sample files would be useful, thanks in advance

**Comment by azerg** [comment]
Sample file: https://onedrive.live.com/redir?resid=83CBBEF6B31667E8%218508

The first url that has _data\data_size_ contains next substring in _location_ field:

> /bdv.bidvertiser.com/bidvertiser.dbm?pid=518501&bid=1293007&RD=13&DIF=1&bd_ref_v=http%3A%2F%2Fhealth

But there are plenty of them.

**Comment by joachimmetz** [comment]
Thanks I'll have a look as soon as time permits.

**Comment by joachimmetz** [comment]
Fixed by: https://github.com/libyal/libmsiecf/commit/d6e36e5610b79443e300662a092ee8057bbaa219

**Comment by joachimmetz** [comment]
The patch and fix is wrong, I'll undo the changes and add other fixes.

**Comment by azerg** [comment]
:unamused:
